Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -2,23 +2,27 @@ workflows:
   ios-build:
     name: iOS build
     environment:
-      # You can use the Xcode version you need; here, we use the latest available
       xcode: latest
       cocoapods: default
-      # Specify the environment variables for the GitHub student account
       vars:
         GITHUB_USER: ${{github.username}}
         GITHUB_TOKEN: ${{github.token}}
-      # Add any additional environment variables you might need
     triggering:
       events:
         - push
         - pull_request
     scripts:
+      - name: Check for Gemfile
+        script: |
+          if [ ! -f Gemfile ]; then
+            echo "Error: Gemfile not found!"
+            exit 1
+          fi
       - name: Install dependencies
         script: |
           gem install bundler
           bundle install
+          cd ios
           bundle exec pod install
       - name: Build iOS app
         script: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/build/Runner.xcarchive
